npmRegistries:
  '//registry.npmjs.org/':
    npmAuthToken: '${NPM_TOKEN:-}'

npmScopes:
  ekim088:
    npmRegistryServer: 'https://registry.npmjs.org'
    npmPublishRegistry: 'https://registry.npmjs.org'
