approvedGitRepositories:
  - '**'

enableScripts: true

nodeLinker: pnp

npmMinimalAgeGate: 0

npmRegistries:
  //registry.npmjs.org/:
    npmAuthToken: '${NPM_TOKEN:-}'

npmScopes:
  ekim088:
    npmPublishRegistry: 'https://registry.npmjs.org'
    npmRegistryServer: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-4.16.0.cjs
